const co_coordinator = [
  {
    id: 0,
    name: "Web Development",
    text: [["Nivas",
      "Saksham Gera",
      "Siddharth",
      "Vatsal Koisa",
      "Ujjawal tripathi",
      "Dharmil Halpati",
      "Vankudothu Deepthi"]]
  },
  {
    id: 1,
    name: "Infra & In House Managerial",
    text: [["Nachiket shah",
    "Ashlok Kumar ",
    "Prince Gamit",
    "Akshat lakum ",
    "Sharansh kashyap",
    "Krutika joshi ",
    "MAHEK PATEL",
    "Tanish Panchal ",
    "Prisha Doshi"],[
    "Aditya Kumar",
    "Anoushka Sharma",
    "KASTURI BHARTI ",
    "Gorfad Jay",
    "Neha",
    "Parthivi Jain",
    "Avinash Shiyal",
    "Ujjwal Gupta",
    "Nanviya zala",
    "Aditya goud "],[
    "Yogeshwari Kant ",
    "Arya",
    "vrinda sonawala",
    "Khushi Chaudhary ",
    "Sai kumar",
    "Ajeet Kumar ",
    "Himanshu singh ",
    "Harsh Sonkar ",
    "Prince Kumar",
    "Jay Kacha "],

    ]
  },

  {
    id: 2,
    name: "Infra & In House Managerial",
    text: [[
      "Shivani Parihar",
      "Md kaif",
      "Nisha Sinha ",
      "Maitri parmar",
      "Garvit Jain",
      "Sneha Prasad ",
      "Aashlesh Pardhi ",
      "Ritul Mishra ",
      "Hritick Kumar",
      "Gaurav singh "],[
      "Jainesh",
      "Shlok Bhagat",
      "Sneha Vishnoi",
      "Dhruv Gautam",
      "Manas Rohit Shouche",
      "Harmandeep Kaur ",
      "Burhanuddin Dadawala",
      "AMISHA SONI ",
      "Srishti Verma",
      "Guguloth Sangeetha"]]
  },

  {
    id: 3,
    name: "Publicity",
    text: [["Parth Desai ",
    "Shrishti arya",
    "Nancy agrawal",
    "Foram Kapadia ",
    "Sneha Kishor hiwrale ",
    "Yashika ",
    "Krish Visalpara ",
    "Mohammed Faizan ",
    "Pritish Mani Tripathi",
    "Abhinandan Sharma"],[
    "Sachin ",
    "Pravesh Jain",
    "Naina bansal",
    "Kushagra Kanchan ",
    "Honey Bohra ",
    "Ravita",
    "Shambhavi Shinde",
    "himani gupta ",
    "Krishna Meghwal ",
    "Anmol "],[
    "Ashok dudi ",
    "Anish kharbas",
    "Garima",
    "Sourabh Yadav ",
    "Sonu kumar",
    "alam ",
    "Himanshu Singh ",
    "Srisailam Renuka",
    "Kodali Apoorva"]]
  },
  {
    id: 4,
    name: "Sponsorship",
    text: [["Ved Patel",
"Moti singh rajpurohit ",
"Megha patel",
"Atish Ranjan ",
"Jigar jat",
"Savan bhatiya",
"Vishal Halwai",
"Sanidhya Gupta",
"Anshika Pattnaik ",
"Nishant Chitakala"],[
"Kashish Maheshwari ",
"Kashish Sharma ",
"PRATYASHA ROUTRA",
"Sohan R. Pagar",
"Shreyansh Parikh",
"Kashish Varma",
"Kartik Srivastava",
"Adarsh Agrahari ",
"Bhagirath suthar",
"Mukesh choudhary"],[
"Harish Khandelwal ",
"Suresh Chaudhary ",
"Chavda Kapidhvaj A",
"Shishir Khairkar",
"Aum Thakkar",
"Yash Patel ",
"Pragya Sharma",
"Qasim Sarwar",
"Shivam Kumar Singh "]]
  },
  {
    id: 5,
    name: "Public Relation",
    text: [["Ritik Lal",
    "Richa Singh ",
    "Saurav Kumar ",
    "ARYAN GUPTA ",
    "Purva Bedse",
    "Anushka Sanjay Ghushe",
    "Chirag charbhe ",
    "Shlok Agrawal ",
    "ESHITA GADWE",
    "Ravish",
    "Vivek singh",
    "C Vaishnavi Reddy"],[
    "Adhya Patel ",
    "Tanishk Varshney ",
    "TIWARI OM",
    "Ronak Dangar ",
    "Saiyam kotadiya ",
    "Jha ashish Mithilesh ",
    "Rishabh jain ",
    "Raghav Lathi ",
    "Isha Tewari",
    "Tanmay chaturvedi",
    "Rocky Nayan",
    "Gourav dadarwal "
    ]]
  },
  {
    id: 6,
    name: "Hospitality",
    text: [["Kashyap Mohanty ",
    "Vishal Mehta ",
    "Amit Prakash",
    "Nirav ",
    "Krishna Ghetia",
    "S Madhukar ",
    "Suraj kr mishra ",
    "Prateek verma ",
    ],["B Ranjith",
    "Mohit ",
    "Tanya Mishra ",
    "Lawkesh Tiwary ",
    "Priyam Chhaparia",
    "Vaishvik Kothia",
    "Aniket Kumar Verma",
    "Om Singh "]]
  },
  {
    id: 7,
    name: "Hospitality",
    text: [[
    "Samarth Chaplot",
    "Sushant Singh ",
    "Manish Khorwal ",
    "Abhishek Shah ",
    "Gaurav Singh",
    "Krunal Patel ",
    "B. Pranith Reddy",
    "Aamena ",
    "Thumar Hemangi Vasantbhai"],[
    "Aditi Garg",
    "Mohit Kumar",
    "Surya Pratap Yadav ",
    "NAMRATA ",
    "Pragvi Parmar ",
    "Sonam ",
    "Anurag Pilankar",
    "Kadimisetti Vagdevi"]]
  },
  {
    id: 8,
    name: "Discipline",
    text: [["Priyanshi patel ",
    "Raju Kumar ",
    "AASHISH GUPTA ",
    "Ashish Rajput ",
    "Lavanya N. Pinjarkar",
    "Prince",
    "Ankush Kumar",
    "Anuradha Singh ",
    "Arvind Singh ",
    "Naresh Anchara "],[
    "Shubham Shrivastava ",
    "Vamshi koushik ",
    "Manish ",
    "Aniket Singh",
    "Arunesh kumar ",
    "Krish Kamble",
    "Jitender Singh Kaswan",
    "Rahul",
    "Upasana Mondal ",
    "Gaurav Nambiar "],[
    "Rohit Singh pal",
    "Aditya Anmol",
    "Aditya Rai",
    "Kushal Barala",
    "GULSHAN",
    "Sahid khan",
    "Aditya Aryan ",
    "Sri laxmi Prasanna"]]
  },
  {
    id: 9,
    name: "Admin & Documentation",
    text: [["Preet Shah ",
    "Desh Deepak Verma ",
    "Sri Vishal Narlanka",
    "Ratnesh Ranjan",
    "Harshit Pandey",
    "Mahir Panjabi ",
    "Mitesh Joshi ",
    "Hritik kumar",
    "Swarukh bagde",
    "Manish raj"],[
    "Adarsh Kumar Srivastava ",
    "Krishna Agrawal",
    "Nisarg khambhati ",
    "Raj kumar",
    "Aryan Baviskar ",
    "Sanvi Sandipika ",
    "Reshav Sharma ",
    "VISHWA LATHIGAR",
    "Chaitanya Singh ",
    "Aman Tiwari"]]
  },
  {
    id: 10,
    name: "Design",
    text: [["Mudra Bhedi",
    "Kashyap Mayank Vijaykumar",
    "Fardeen Khan",
    "Devanshi Thaker",
    "Abhishek Verma ",
    "Dhruv Chheda",
    "Ruchir saraf "],[
    "Adarsh Tiwari ",
    "Hetvi Modi",
    "Nirav Sonagara ",
    "Savni ",
    "Vaibhav Meena",
    "Dhub sufiya "]]
  },
  {
    id: 11,
    name: "Think Tank",
    text: [["Sharma Mitesh",
    "Aditya Chauhan",
    "Aman Dana",
    "Dhairya Vaidya ",
    "OM KULTHE",
    "Pratham Bhatt ",
    "Ayukta labh",
    "Mahek Desai",
    "Viresh Sancheti"],[
    "Abhishek Pratap Singh",
    "Akshay Amin ",
    "PRATEEK MISHRA",
    "ViveK Poonia",
    "Priya swami",
    "Nisha meena ",
    "SHUBHAM KUMAR",
    "Balgari Ruchitha"]]
  },
  {
    id: 12,
    name: "Media Cell & Content Writing",
    text: [["Stuti singh ",
      "Tripti Sharma ",
      "Prashant Shukla ",
      "Sebastian John ",
      "Yashaswini Sharma ",
      "Harini Mandapaka ",
      "Shruthi Alige "],[
      "Pesala Eswar ",
      "Misbah Shaikh ",
      "Bittu Kumar ",
      "Mihirsinh Chauhan ",
      "Khushi Singh ",
      "Preesha Sheth ",
      "Shrushti Meshram"]]
  },
  {
    id: 13,
    name: "Cinematography & Video Editing",
    text: [["Jbin Kapadia ",
      "Harsh Joshi ",
      "Asmit Kmar ",
      "Sjal kindarkhediya ",
      "K. Chetan teja ",
      "Sanskar Trivedi ",
      "Pankaj Vaniya "],[
      "Sraj Parmar ",
      "Aditya Bhatiya ",
      "Abhay Raj Paraliya ",
      "Priya Patel ",
      "Jignesh Meena ",
      "Karan Singh ",
      "Ishant Patil"]]
  },

]

export {co_coordinator};